server {
    listen 3000;
    root /usr/share/nginx/html;
    index index.html;

    location /api/ {
        proxy_pass https://daring-balance-production-fc0c.up.railway.app/api/;
        proxy_ssl_server_name on;
        proxy_set_header Host daring-balance-production-fc0c.up.railway.app;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /hubs/ {
        proxy_pass https://daring-balance-production-fc0c.up.railway.app/hubs/;
        proxy_ssl_server_name on;
        proxy_set_header Host daring-balance-production-fc0c.up.railway.app;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
